# Generated by Django 4.1.3 on 2022-11-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('poids', models.CharField(max_length=50)),
                ('taille', models.CharField(max_length=50)),
                ('imc', models.CharField(max_length=50)),
            ],
        ),
    ]
