# Generated by Django 4.1.3 on 2022-11-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imc',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='poids',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='taille',
            field=models.IntegerField(max_length=50),
        ),
    ]
