# Generated by Django 4.1.3 on 2022-11-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0003_remove_person_imc_alter_person_poids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
