# Generated by Django 4.1.3 on 2022-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0004_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='poids',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='taille',
            field=models.IntegerField(max_length=50),
        ),
    ]
