# Generated by Django 4.1.3 on 2022-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0005_alter_person_poids_alter_person_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='poids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='taille',
            field=models.IntegerField(default=0),
        ),
    ]
